tasks.build = "cargo build --all"
tasks.build-release = "cargo build --all --release"
tasks.format = "cargo fmt -- --all"
tasks.lint = [
  "cargo clippy --all -- -D warnings",
  "cargo fmt --all -- --check",
]
tasks.release = "cargo release"

[tasks.test]
run = "cargo test --all"
depends = ['build']

[tasks.ci]
depends = ["build", "lint", "test"]
